name: mausafe_v0
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  location: "^1.3.4"
  map_view: ^0.0.14
  #map_view:
  #  git:
  #    url: git://github.com/Eimji/flutter_google_map_view.git
  access_settings_menu: "^0.0.1"
  http: "^0.11.3+16"
  progress_hud: "^1.0.0"
  device_info: "^0.2.1"
  shared_preferences: "^0.4.2"
  url_launcher: "^3.0.3"
  camera: ^0.5.0
  path_provider: ^0.5.0+1
  fluttertoast: ^2.2.6

  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
  - images/pic_avatar.jpg
  - images/drawer_heartbeat.jpg
  - images/accident.png
  - images/applogo.png
  - images/arrangement.png
  - images/assault.png
  - images/coastguard.png
  - images/drowning.png
  - images/fire.png
  - images/fireman.png
  - images/general_logo.png
  - images/health.png
  - images/paramedic.png
  - images/policeman.png
  - images/thief.png
  - images/track_me.png
  - images/ambulance.png
  - images/firetruck.png
  - images/boat.png
  - images/black_avatar.png
  - images/black_avatar_3.png
  - images/black_avatar_4.png
  - images/anonymous_avatar.png
  - images/witness/Building_fire.png
  - images/witness/car_fire.png
  - images/witness/Commercial.png
  - images/witness/Commercial_2.png
  - images/witness/forest_fire.png
  - images/witness/industrial.png
  - images/witness/Residential.png
  - images/witness/Building_fire.png
  - images/witness/car_fire.jpg
  - images/witness/forest_fire.png
  - images/hospital.png
  - images/eye.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
